server:
  port: 9527
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}

    gateway:
      routes:
        - id: foodService                # 路由ID, 要求唯一
          uri: lb://food-service
          predicates:
            - Path=/food/**    # 断言, 路径匹配后进行路由

        - id: addressService                # 路由ID, 要求唯一
          uri: lb://address-service
          predicates:
            - Path=/address/**    # 断言, 路径匹配后进行路由

        - id: userService                # 路由ID, 要求唯一
          uri: lb://user-service
          predicates:
            - Path=/user/**    # 断言, 路径匹配后进行路由

        - id: businessService                # 路由ID, 要求唯一
          uri: lb://business-service
          predicates:
            - Path=/business/**    # 断言, 路径匹配后进行路由

        - id: orderService                # 路由ID, 要求唯一
          uri: lb://order-service
          predicates:
            - Path=/orders/**    # 断言, 路径匹配后进行路由

        - id: cartService                # 路由ID, 要求唯一
          uri: lb://cart-service
          predicates:
            - Path=/cart/**    # 断言, 路径匹配后进行路由

